name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build And Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_GRASS_0C1E0D900 }}
          action: upload
          app_location: "/"        # index.html 在根目錄的話就用 "/"
          skip_app_build: true     # <<< 關鍵：純靜態務必跳過建置
          output_location: ""      # 跳建置時請留空
          api_location: ""         # 沒 Functions 留空
